server:
  port: 8888
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    name: seckill
    url: jdbc:mysql://localhost:3306/seckill?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
    #使用 druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver